# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

### Site settings
title: Daniel Griffin
description: Critical and otherwise writings for today and yesterday.

# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

timezone: America/New_York

### Serve options
host: 0.0.0.0
port: 4000
detach: false
# baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown

permalink: "/:year/:title/"
